# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rostopic_hz.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rostopic_hz.proto\"\x07\n\x05\x45mpty\"\x1e\n\tSuccesses\x12\x11\n\tsuccesses\x18\x01 \x03(\x08\"\x18\n\x06Topics\x12\x0e\n\x06topics\x18\x01 \x03(\t\"1\n\x12RostopicHzResponse\x12\x0e\n\x06topics\x18\x01 \x03(\t\x12\x0b\n\x03hzs\x18\x02 \x03(\x02\x32\xa6\x01\n\rRostopicHzRpc\x12-\n\njoinClient\x12\x06.Empty\x1a\x13.RostopicHzResponse\"\x00\x30\x01\x12\"\n\taddTopics\x12\x07.Topics\x1a\n.Successes\"\x00\x12!\n\x0cremoveTopics\x12\x07.Topics\x1a\x06.Empty\"\x00\x12\x1f\n\x0bstopMonitor\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_SUCCESSES = DESCRIPTOR.message_types_by_name['Successes']
_TOPICS = DESCRIPTOR.message_types_by_name['Topics']
_ROSTOPICHZRESPONSE = DESCRIPTOR.message_types_by_name['RostopicHzResponse']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'rostopic_hz_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Successes = _reflection.GeneratedProtocolMessageType('Successes', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESSES,
  '__module__' : 'rostopic_hz_pb2'
  # @@protoc_insertion_point(class_scope:Successes)
  })
_sym_db.RegisterMessage(Successes)

Topics = _reflection.GeneratedProtocolMessageType('Topics', (_message.Message,), {
  'DESCRIPTOR' : _TOPICS,
  '__module__' : 'rostopic_hz_pb2'
  # @@protoc_insertion_point(class_scope:Topics)
  })
_sym_db.RegisterMessage(Topics)

RostopicHzResponse = _reflection.GeneratedProtocolMessageType('RostopicHzResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROSTOPICHZRESPONSE,
  '__module__' : 'rostopic_hz_pb2'
  # @@protoc_insertion_point(class_scope:RostopicHzResponse)
  })
_sym_db.RegisterMessage(RostopicHzResponse)

_ROSTOPICHZRPC = DESCRIPTOR.services_by_name['RostopicHzRpc']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=21
  _EMPTY._serialized_end=28
  _SUCCESSES._serialized_start=30
  _SUCCESSES._serialized_end=60
  _TOPICS._serialized_start=62
  _TOPICS._serialized_end=86
  _ROSTOPICHZRESPONSE._serialized_start=88
  _ROSTOPICHZRESPONSE._serialized_end=137
  _ROSTOPICHZRPC._serialized_start=140
  _ROSTOPICHZRPC._serialized_end=306
# @@protoc_insertion_point(module_scope)
